// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void InserirTipoServicoVlido() {
    driver.Navigate().GoToUrl("https://localhost:44387");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.Id("login")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".card-body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".card-body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".card-body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector(".card-body")).Click();
    driver.FindElement(By.CssSelector(".login-page")).Click();
    driver.FindElement(By.CssSelector(".card-body")).Click();
    driver.FindElement(By.Id("password")).SendKeys("W@gner2018");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".fa-lock")).Click();
    driver.FindElement(By.Id("showpass")).Click();
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.CssSelector(".login-page")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".nav:nth-child(14) p")).Click();
    driver.FindElement(By.LinkText("Novo Tipo de Serviço")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Marcenaria");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
