// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void AlterarTipoPatrimnioVlido() {
    driver.Navigate().GoToUrl("https://localhost:5001/");
    driver.Manage().Window.Size = new System.Drawing.Size(1920, 1053);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_Email")).Click();
    driver.FindElement(By.Id("Input_Email")).SendKeys("daniel17sants@gmail.com");
    driver.FindElement(By.Id("password")).Click();
    driver.FindElement(By.Id("password")).SendKeys("D@n123456");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.LinkText("Tipo do Patrimônio")).Click();
    driver.FindElement(By.CssSelector(".odd:nth-child(3) .fa-edit")).Click();
    driver.FindElement(By.Id("Nome")).Click();
    driver.FindElement(By.Id("Nome")).SendKeys("Elétrico");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
  }
}
